---
- name: "Collect instance info of {{ item.name }}"
  openstack.cloud.server_info:
    name: "{{ os_default_prefix }}{{ item.name }}"
  register: info

- name: Redo till instance info available
  when:  (info.servers | length == 0) or (info.servers[-1].access_ipv4 | length == 0)
  ansible.builtin.include_tasks: helper/wait_till_instance_info_avail.yml