---
- name: Test connection
  ansible.builtin.ping:
  register: ping
  ignore_errors: true
  ignore_unreachable: true

- name: Redo test connection
  when: ping.unreachable is defined
  ansible.builtin.include_tasks: test_ssh_connection.yml